"""
Compile the appliance profiles into the firmware.

They travel with the binary rather than living on a filesystem so that an OTA
update carries firmware and profiles together. A separately flashed data
partition would let the two drift apart, and once the board is behind an
appliance there is no way to correct that.

Only the signature -- the distinct dest/cmd pairs -- is needed to recognise which
appliance is on the bus, so it is precomputed here. Parsing every profile at
startup just to compare addresses would be wasteful.

(C) 2026 Jonas Brüstel
Licensed under the GNU General Public License version 3.0.
"""

import json
import pathlib
import sys

Import("env")  # noqa: F821  (injected by PlatformIO)

ROOT = pathlib.Path(env.subst("$PROJECT_DIR"))  # noqa: F821
SRC = ROOT / "profiles"
OUT = ROOT / "components" / "app_profiles" / "src" / "profiles_asset.c"

sys.path.insert(0, str(ROOT / "tools"))
import profile_lib as lib  # noqa: E402


def c_string(text: str) -> str:
    """JSON as a C string literal, escaped and split into lines the compiler
    will accept -- some profiles are several kilobytes."""
    out, line = [], []
    for ch in text:
        if ch == '"':
            line.append('\\"')
        elif ch == "\\":
            line.append("\\\\")
        elif ch == "\n":
            line.append("\\n")
        elif ch == "\r":
            continue
        elif ord(ch) < 0x20:
            line.append(f"\\x{ord(ch):02x}")
        else:
            line.append(ch)
        if len(line) > 100:
            out.append('"' + "".join(line) + '"')
            line = []
    if line:
        out.append('"' + "".join(line) + '"')
    return "\n  ".join(out) if out else '""'


def generate():
    # Bases hold shared decoding and are not appliances in their own right, so
    # they are resolved into the models rather than offered for selection.
    # Bases are embedded too, as generic fallbacks: an appliance of the right
    # family whose exact model nobody has mapped still decodes correctly, it just
    # reports codes rather than programme names.
    files = sorted(SRC.glob("*.json")) + sorted((SRC / "base").glob("*.json")) \
        if SRC.is_dir() else []
    if not files:
        print("gen_profiles_asset: no profiles found -- firmware will ship without any")

    entries, total = [], 0
    for path in files:
        try:
            doc = lib.resolve(lib.load(path), SRC)
        except json.JSONDecodeError as e:
            raise SystemExit(f"gen_profiles_asset: {path.name} is not valid JSON: {e}")
        except (FileNotFoundError, KeyError) as e:
            raise SystemExit(f"gen_profiles_asset: {path.name}: {e}")

        meta = doc.get("profile", {})
        pairs = sorted({(int(str(e["match"]["dest"]), 0) << 16) | int(str(e["match"]["cmd"]), 0)
                        for e in doc.get("entities", []) if "match" in e})

        compact = json.dumps(doc, separators=(",", ":"), ensure_ascii=False)
        total += len(compact.encode("utf-8"))

        entries.append({
            "generic": bool(meta.get("generic")),
            "id": meta.get("id", path.stem),
            "model": meta.get("model", ""),
            "product": meta.get("product", ""),
            "appliance": meta.get("appliance", "unknown"),
            "entities": len(doc.get("entities", [])),
            "pairs": pairs,
            "json": compact,
        })

    parts = [
        "/* Generated by tools/gen_profiles_asset.py from profiles/ -- do not edit. */\n",
        '#include "appprofiles/Profiles.h"\n\n',
    ]

    for i, e in enumerate(entries):
        parts.append(f"static const uint32_t sig_{i}[] = {{" +
                     ",".join(f"0x{p:08x}" for p in e["pairs"]) + "};\n")
        parts.append(f"static const char json_{i}[] =\n  {c_string(e['json'])};\n\n")

    parts.append("const bsh_profile_t bsh_profiles[] = {\n")
    for i, e in enumerate(entries):
        parts.append(
            f'  {{"{e["id"]}", "{e["model"]}", "{e["product"]}", "{e["appliance"]}", '
            f'{e["entities"]}, sig_{i}, {len(e["pairs"])}, json_{i}, sizeof(json_{i}) - 1, '
            f'{"true" if e["generic"] else "false"}}},\n')
    parts.append("};\n")
    parts.append(f"const unsigned bsh_profile_count = {len(entries)};\n")

    text = "".join(parts)
    if OUT.is_file() and OUT.read_text(encoding="utf-8") == text:
        print(f"gen_profiles_asset: unchanged ({len(entries)} profiles, {total // 1024} KB)")
        return

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(text, encoding="utf-8")
    print(f"gen_profiles_asset: {len(entries)} profiles, {total // 1024} KB of JSON")


generate()
